### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ksv1986** [ksv1986/wsldskmnt#1]
- [x] Read and display wsl.exe output
- [x] Enumerate partitions and add "Mount partition" menu entries
- [x] Add "Open" menu entry for mounted partitions
- [x] Filter windows partitions
- [x] Hot plugging support
